version: '3.7'
services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
  db:
    image: postgres
    environment:
      - POSTGRES_USER=ceon
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=mydb
    ports:
      - "127.0.0.1:5432:5432"
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/app
    links:
      - db
      - redis
    depends_on:
      - db
      - redis